name: Deploy specific HTML

on:
  workflow_dispatch:
    inputs:
      html_path:
        description: "Path to HTML file relative to repo root (e.g., week1-assignment/html/index.html)"
        required: true
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Stage requested HTML and its assets
        run: |
          set -e
          FILE="${{ github.event.inputs.html_path }}"
          DIR=$(dirname "$FILE")

          echo "Using file: $FILE"
          echo "Containing dir: $DIR"

          mkdir site
          cp -r "$DIR"/* site/

          # Ensure entry file is index.html
          if [ ! -f site/index.html ]; then
            mv "site/$(basename "$FILE")" site/index.html
          fi

          echo "=== Site content ==="
          ls -la site

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
