name: Deploy assignment to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      html_path:
        description: 'Path to HTML file (relative to repo root, e.g. week1-assignment/html/data_storage_types.html)'
        required: true
        default: 'week1-assignment/html/data_storage_types.html'
        type: string
      subdir_name:
        description: 'Subfolder under Pages root (e.g. data_storage_types)'
        required: true
        default: 'data_storage_types'
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Stage site into chosen subfolder
        shell: bash
        run: |
          set -euo pipefail

          HTML_PATH="${{ github.event.inputs.html_path }}"
          SUBDIR="${{ github.event.inputs.subdir_name }}"

          echo "HTML_PATH=$HTML_PATH"
          echo "SUBDIR=$SUBDIR"

          if [ ! -f "$HTML_PATH" ]; then
            echo "ERROR: File not found: $HTML_PATH" >&2
            exit 1
          fi

          SRC_DIR="$(dirname "$HTML_PATH")"
          HTML_FILE="$(basename "$HTML_PATH")"

          # Clean and prepare staging
          rm -rf site
          mkdir -p "site/$SUBDIR"

          # Copy source folder into subdir
          cp -R "$SRC_DIR"/. "site/$SUBDIR/"

          # Ensure index.html exists
          if [ ! -f "site/$SUBDIR/index.html" ]; then
            mv "site/$SUBDIR/$HTML_FILE" "site/$SUBDIR/index.html"
          fi

          # Add 404.html inside subdir for safety
          cp "site/$SUBDIR/index.html" "site/$SUBDIR/404.html" || true

          # ---- Root redirect to subdir ----
          cat > site/index.html <<EOF
          <!doctype html>
          <html><head>
            <meta charset="utf-8">
            <meta http-equiv="refresh" content="0; url=./$SUBDIR/">
            <script>location.replace('./$SUBDIR/');</script>
            <title>Redirecting…</title>
          </head>
          <body>
            <p>Redirecting to <a href="./$SUBDIR/">./$SUBDIR/</a>…</p>
          </body></html>
          EOF

          # Root 404 also redirects
          cp site/index.html site/404.html

          echo "=== Final site structure (top two levels) ==="
          find site -maxdepth 2 -type f | sort

          # Guards
          test -f "site/$SUBDIR/index.html" || (echo "ERROR: index.html missing in $SUBDIR" >&2; exit 2)
          test -f "site/index.html" || (echo "ERROR: root redirect missing" >&2; exit 3)

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Print final URL
        run: |
          echo "✅ Your assignment is live at:"
          echo "${{ steps.deployment.outputs.page_url }}${{ github.event.inputs.subdir_name }}/"
