name: Deploy week1 HTML to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'week1-assignment/html/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Copy just the site content from your subfolder into a staging dir
      - name: Prepare site
        run: |
          mkdir -p site
          cp -r week1-assignment/html/* site/

      # Upload that staging dir as the Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
