name: Deploy assignment to a subpath on GitHub Pages

on:
  push:
    branches: [ main ]
    # Auto-deploy when the week1 html folder changes
    paths:
      - 'week1-assignment/html/**'
  workflow_dispatch:
    inputs:
      html_path:
        description: 'Path to the HTML file (relative to repo root)'
        required: false
        default: 'week1-assignment/html/data_storage_types.html'
        type: string
      subdir_name:
        description: 'Subfolder under Pages root to publish into'
        required: false
        default: 'data_storage_types'
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Resolve inputs
        id: vars
        shell: bash
        run: |
          # Defaults (used for push-triggered runs)
          DEF_HTML='week1-assignment/html/data_storage_types.html'
          DEF_SUB='data_storage_types'

          # Take manual inputs when present
          HTML_IN='${{ github.event.inputs.html_path }}'
          SUB_IN='${{ github.event.inputs.subdir_name }}'

          HTML_PATH="${HTML_IN:-$DEF_HTML}"
          SUBDIR_NAME="${SUB_IN:-$DEF_SUB}"

          echo "html_path=$HTML_PATH" >> "$GITHUB_OUTPUT"
          echo "subdir_name=$SUBDIR_NAME" >> "$GITHUB_OUTPUT"

      - name: Stage subdirectory site
        shell: bash
        run: |
          set -euo pipefail

          HTML_PATH='${{ steps.vars.outputs.html_path }}'
          SUBDIR='${{ steps.vars.outputs.subdir_name }}'

          echo "Selected HTML: $HTML_PATH"
          echo "Publishing under subfolder: $SUBDIR"

          if [ ! -f "$HTML_PATH" ]; then
            echo "ERROR: File not found: $HTML_PATH" >&2
            exit 1
          fi

          SRC_DIR="$(dirname "$HTML_PATH")"
          HTML_FILE="$(basename "$HTML_PATH")"

          # Create the site layout: site/<SUBDIR>/*
          rm -rf site
          mkdir -p "site/$SUBDIR"

          # Copy everything from the HTML's containing directory
          cp -R "$SRC_DIR"/. "site/$SUBDIR/"

          # Ensure entry file is index.html at site/<SUBDIR>/index.html
          if [ ! -f "site/$SUBDIR/index.html" ]; then
            mv "site/$SUBDIR/$HTML_FILE" "site/$SUBDIR/index.html"
          fi

          # Optional: for SPAs/deep links inside that subdir
          if [ ! -f "site/$SUBDIR/404.html" ]; then
            cp "site/$SUBDIR/index.html" "site/$SUBDIR/404.html" || true
          fi

          echo "=== Deployed folder tree ==="
          find site -maxdepth 2 -type f -print | sort

          # Final guard
          test -f "site/$SUBDIR/index.html" || (echo "index.html missing in $SUBDIR" >&2; exit 2)

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
